services:

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # https://hub.docker.com/r/amazon/dynamodb-local
  dynamodb:
    image: amazon/dynamodb-local:2.6.0
    restart: always
    ports:
      - ${DYNAMODB_PORT}:8000

  # https://hub.docker.com/r/clickhouse/clickhouse-server
  clickhouse:
    image: clickhouse/clickhouse-server:25.3-alpine
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ports:
      - ${CLICKHOUSE_PORT}:8123
    volumes:
      - ./docker/clickhouse/data:/var/lib/clickhouse
      - ./docker/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  # https://hub.docker.com/r/confluentinc/cp-zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  # https://hub.docker.com/r/confluentinc/cp-kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.5
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOPICS: ${KAFKA_TOPICS} # list of topics Comma-separated to create
    command: sh -c "((sleep 15 && bash /docker-entrypoint-initdb.d/init.sh)&) && /etc/confluent/docker/run ">
    volumes:
      - ./docker/kafka/init.sh:/docker-entrypoint-initdb.d/init.sh